### ISSUE TITLE
setup.py: Use VERSION variable

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-decorators#11]
So, first of it makes sense to have something like `<pkg_name>.__version__` as lots of devs use this to check the version without using pip. (Like in the code)
Also, you use `1.1.0` twice in setup.py: Once for the `download_url` and once for the `version`. This means you will be changing the version twice for every release. Hence, it makes sense to add this as a variable and reuse in both places.

If you do the `VERSION` file system like how coala and coala-bears does it, you can directly make rultor make dev releases for you for every PR merge. (Which I think is cool, but not required).

**Comment by Adrianzatreanu** [comment]
i dont understand quite how, sorry

**Comment by Adrianzatreanu** [comment]
nevermind, ill jsut remove the download URL as i find it useless, im going to take the version constant for the version.
