### ISSUE TITLE
@lazyproperty

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala-decorators#18]
We need this sooner or later for coala, as our cached file object (that shall cache the contents as string, presplitted or maybe even a `lower()` version)

**Comment by Adrianzatreanu** [comment]
@Makman2 You have opened the issue in the wrong repo, please refer to https://gitlab.com/coala/coala-decorators/ as we have migrated :)

**Comment by Makman2** [comment]
Thanks :)
Migrated to https://gitlab.com/coala/coala-decorators/issues/3 .
