### ISSUE TITLE
unittest extension: `skipIfExecutableNotFound`

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala-decorators#19]
Useful for tests that rely on certain executables being in path. would effectively boil down to this:
```python
import shutil
def skipIfExecutableNotFound(executable):
    return unittest.skipIf(shutil.which(executable) is None, executable + " is not installed.")
```

**Comment by Adrianzatreanu** [comment]
https://gitlab.com/coala/coala-decorators !!!!!!!!!

**Comment by Adrianzatreanu** [comment]
we moved there, Mischa :(

**Comment by Makman2** [comment]
ahh shit I forget that everytime...

**Comment by Makman2** [comment]
moved to https://gitlab.com/coala/coala-decorators/issues/5
