### ISSUE TITLE
Package name !

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-decorators#7]
The package name chosen here is `coala-decorators`.

This cannot be imported ! 

```
>>> import coala-decorators
  File "<stdin>", line 1
    import coala-decorators
                ^
SyntaxError: invalid syntax
```
Python will think the hyphen is a minus sign. Package names need to be lowercase and should use `_` according to pep guidelines.

**Comment by AbdealiJK** [comment]
For completeness, if you really really want to add a `-` in the package name, the way to import that is:
```
>>> __import__('coala-decorators')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named coala-decorators
```
^ Where the `-` is not taken as a subtraction sign.

**Comment by Makman2** [comment]
what the heck we don't want `__import__(...)` :D :D
We need to change the name, let's replace the - with an underscore
